[package]
name = "dawnstore-core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
jsonschema.workspace = true
sqlx.workspace = true
dawnstore-lib = { path = "../dawnstore-lib" }
