[package]
name = "dawnstore-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
chrono.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
schemars.workspace = true
jsonschema.workspace = true
sqlx.workspace = true
dawnstore-core = { path = "../dawnstore-core" }
dawnstore-lib = { path = "../dawnstore-lib" }
